language: node_js
node_js:
  - "lts/*"

cache: yarn
script: yarn test

# We build PRs, but don't trigger separate builds for the PR from the branch.
branches:
  only:
    - master

webhooks:
  urls:
    - https://webhooks.gitter.im/e/8ef32b15db0c4866eb06
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always

