language: node_js
node_js:
  - "lts/*"

cache: yarn
script:
  - yarn test
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then yarn run doc; fi

# We build PRs, but don't trigger separate builds for the PR from the branch.
branches:
  only:
    - master
