name: Publish Docs

on:
  release:
  workflow_dispatch:

jobs:
  publish:
    name: 'Build and publish docs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1

      - run: yarn install --frozen-lockfile --non-interactive

      - name: Build docs
        run: yarn doc

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: docs-dist
